### ISSUE TITLE
Actions not showing on Ios 10.3 Simulator

### ISSUE THREAD

**Issue by buymybm100** [DavidBriglio/cordova-ios10-simple-notification#4]
Hi, 

Thanks for this plugin. Does it work on the Simulator ?  I am getting the Alert but not the buttons.

  cordova.plugins.ios10.simpleNotification.schedule("1", "Title", "Subtitle",
        "New Notification!",
        3.0, "Payload", "Action 1", "Action 2");

Best regards,
Beemer

**Comment by DavidBriglio** [comment]
I have not tried it on the simulator. What target device are you using? I will try some tests and get back to you.

**Comment by buymybm100** [comment]
David, it's my problem. Sorry ! I didn't know you had to 'expand' the Notification to show the Buttons. They do work. Thanks for looking !

Best regards,
Beemer
